name: Deploy to Google Cloud

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
        
      - name: Install Frontend Dependencies
        run: cd frontend && npm ci
        
      - name: Build Frontend
        run: cd frontend && npm run build
        
      - name: Deploy Frontend to Firebase Hosting
        run: |
          cd frontend
          firebase deploy --only hosting --project ${{ secrets.GCP_PROJECT_ID }} --token ${{ secrets.FIREBASE_TOKEN }}
        
      - name: Install Backend Dependencies
        run: cd backend && npm ci
        
      - name: Deploy Backend to Cloud Run
        run: |
          cd backend
          gcloud builds submit --config cloudbuild.yaml --project ${{ secrets.GCP_PROJECT_ID }}
          
      - name: Deploy Firestore Rules
        run: firebase deploy --only firestore:rules --project ${{ secrets.GCP_PROJECT_ID }} --token ${{ secrets.FIREBASE_TOKEN }}